<div class="row">
	<div class="col-lg-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<?php echo $this->partial('page-title', array(
					'title' => $this->model->name,
					'model' => $this->model,
					'crud'	=> $this->crud,
				)); ?>
			</div>
			<div class="panel-body">
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Description'); ?></dt>
					<dd><?php echo $this->prettyTextFormat($this->model->description); ?></dd>
					<dt><?php echo $this->translate('Last Contacted'); ?></dt>
					<dd><?php echo $this->prettyTime($this->model->last_contacted); ?></dd>
					<dt><?php echo $this->translate('Assigned To'); ?></dt>
					<dd><?php echo $this->prettyUser($this->model->assigned_to); ?></dd>
				</dl>
				<div class="text-right"><?php echo $this->partial('info/authorship', array('model' => $this->model)); ?></div>
			</div>
		</div>
	</div>
	<div class="col-lg-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title"><?php echo $this->translate('Contact History'); ?></h2>
			</div>
			<div class="panel-body">
			</div>
		</div>
	</div>
</div>
