<h2 class="text-danger"><?php echo $this->translate('Warning! Your login cookie has been stolen!'); ?></h2>
<p><?php echo $this->translate("You have been logged out because we have detected a possible attempt to access your account.
This type of attack can happen if the security of your browser's cookies has been compromised."); ?></p>
<h4><?php echo $this->translate('What should I do?'); ?></h4>
<p><?php echo $this->translate("First of all, don't panic. Access to sensitive data and the ability to change your login details
requires password authentication, so a cookie-thief has only limited access to your account,
which will now have been revoked. It is recommended you ensure the integrity of the machine
you are using before attempting to log back in."); ?></p>
