<?php
	$element = $this->element;
	$model = $this->model;
	$property = $element->getName();
?>
<label class="col-lg-<?php echo $this->leftColWidth; ?> control-label" for="<?php echo $element->getAttribute('id'); ?>"><?php echo $element->getLabel(); ?></label>
<div class="col-lg-<?php echo $this->rightColWidth; ?>">
	<div class="input-group">
		<input id="<?php echo $element->getAttribute('id'); ?>_ac" type="text" class="autocomplete form-control" data-target="#<?php echo $element->getAttribute('id'); ?>" value="<?php echo $element->getValue(); ?>">
		<span class="input-group-addon glyphicon glyphicon-search"></span>
	</div>
	<?php echo $this->formElement($element); ?>
	<?php if ($this->formElementErrors($element)): ?>
	<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
	<?php endif; ?>
</div>
<script type="text/javascript">
	$(function () {
		$(document).ready(function () {
			$('#<?php echo $element->getAttribute('id'); ?>').hide();
			$('#<?php echo $element->getAttribute('id').'_ac'; ?>').autocomplete({
				source: <?php echo json_encode($this->url($element->getSource(), $element->getSourceOptions())); ?>,
			});
		});
	});
</script>