<div class="col-lg-offset-<?php echo $this->leftColWidth; ?> col-lg-<?php echo $this->rightColWidth; ?>">
	<label class="checkbox" for="<?php echo $element->getAttribute('id'); ?>">
		<?php echo $this->formElement($element); ?> <?php echo $element->getLabel(); ?>
	</label>
	<?php if ($this->formElementErrors($element)): ?>
	<span class="help-inline"><?php echo $this->formElementErrors($element); ?></span>
	<?php endif; ?>
</div>
