<label class="col-lg-<?php echo $this->leftColWidth; ?> control-label" for="<?php echo $element->getAttribute('id'); ?>"><?php echo $element->getLabel(); ?></label>
<div class="col-lg-<?php echo $this->rightColWidth; ?>">
	<p class="form-control-static">
		<?php if ($element->getEscapeHtml()): ?>
		<?php echo $this->escapehtml($element->getValue()); ?>
		<?php else: ?>
		<?php echo $element->getValue(); ?>
		<?php endif; ?>
		<?php if ($element->getChangeUrl()): ?>
		(<a href="<?php echo $element->getChangeUrl(); ?>"><?php echo $this->translate('Change'); ?></a>)
		<?php endif; ?>
	</p>
	<?php if ($this->formElementErrors($element)): ?>
	<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
	<?php endif; ?>
</div>