<label class="col-lg-<?php echo $this->leftColWidth; ?> control-label<?php if ($element->getAttribute('required')): ?> required<?php endif; ?>" for="<?php echo $element->getAttribute('id'); ?>">
	<?php echo $element->getLabel(); ?>
</label>
<div class="col-lg-<?php echo $this->rightColWidth; ?>">
	<?php echo $this->formElement($element); ?>
	<?php if ($this->formElementErrors($element)): ?>
	<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
	<?php endif; ?>
</div>