<p>Someone has requested a password reset for your <?php echo $this->translate('Omelettes Application'); ?> account.</p>

<p>If it was not you, please ignore this message. Otherwise, visit the link below to change the password for your account.</p>

<p>This action must be completed within three hours of the request being generated.</p>

<a href="<?php echo $this->basePath($this->url('reset-password', array('user_key' => $this->user_key, 'password_reset_key' => $this->password_reset_key))); ?>">Click here to change your password</a>