Someone has requested a password reset for your <?php echo $this->translate('Omelettes Application'); ?> account.

If it was not you, please ignore this message. Otherwise, visit the link below to change the password for your account.

This action must be completed within three hours of the request being generated.

<?php echo $this->basePath($this->url('reset-password', array('user_key' => $this->user_key, 'password_reset_key' => $this->password_reset_key))); ?>