<?php echo $this->partial('page-title', array(
	'title' => $this->model->labelPlural . ' Resource',
	'model' => $this->model,
	'crud'	=> $this->crud,
)); ?>

<div class="paper">
	<dl class="dl-horizontal">
		<dt><?php echo $this->translate('Created'); ?></dt>
		<dd><?php echo $this->prettyTime($this->model->created); ?></dd>
	</dl>
	
	<h4>Resource Fields</h4>
	<?php echo $this->tabulate($this->fields); ?>
</div>
