<?php
	$element = $this->element;
	$elementType = $element->getAttribute('type');
	if (!in_array($elementType, array('submit'))) {
		$element->setAttribute('class', 'form-control ' . $element->getAttribute('class'));
	}
?>
<div class="form-group<?php if ($this->formElementErrors($element)) echo " has-error"; ?>">
	<?php echo $this->partial(
			'partial/form/element-horizontal/' . $elementType . '.phtml',
			array(
				'element'		=> $element,
				'leftColWidth'	=> $leftColWidth,
				'rightColWidth'	=> $rightColWidth,
				'model'			=> $this->model,
			)); ?>
</div>
