<?php

use Zend\Form\Fieldset;
use Omelettes\Form\Fieldset\SubmitFieldset;
use Tactile\Form\Fieldset\DateTimeFieldset;

$leftColWidth = 2;
$rightColWidth = 4;

$form = $this->form;
$form->setAttributes(array(
	'action'	=> $this->url(null, array(), array(), true),
	'class'		=> $form->getAttribute('name') . ' form-horizontal',
));
$form->prepare();
echo $this->form()->openTag($form);

?>
<?php foreach ($form as $element): ?>
<?php if ($element instanceof SubmitFieldset): ?>
<?php echo $this->partial(
		'partial/form/fieldset-submit.phtml',
		array(
			'fieldset' => $element,
			'leftColWidth'	=> $leftColWidth,
			'rightColWidth'	=> $rightColWidth,
		)); ?>
<?php elseif ($element instanceof DateTimeFieldset): ?>
<?php echo $this->partial(
		'partial/form/datetime-fieldset-horizontal.phtml',
		array(
			'fieldset' => $element,
			'leftColWidth'	=> $leftColWidth,
			'rightColWidth'	=> $rightColWidth,
		)); ?>
<?php elseif ($element instanceof Fieldset): ?>
<?php echo $this->partial(
		'partial/form/fieldset-horizontal.phtml',
		array(
			'fieldset' => $element,
			'leftColWidth'	=> $leftColWidth,
			'rightColWidth'	=> $rightColWidth,
		)); ?>
<?php else: ?>
<?php echo $this->partial(
		'partial/form/group-horizontal.phtml',
		array(
			'element'		=> $element,
			'leftColWidth'	=> $leftColWidth,
			'rightColWidth'	=> $rightColWidth,
		)); ?>
<?php endif; ?>
<?php endforeach; ?>
<?php echo $this->form()->closeTag($form); ?>
