<head>
	<?php
		echo $this->headTitle($this->translate('Omelett.es Application'))
			->setSeparator(' - ')
			->setAutoEscape(false);
	?>
		

	<!-- Meta -->
	<?php
		echo $this->headMeta()
			->setCharset('utf-8')
			->appendName('viewport', 'width=device-width, initial-scale=1.0');
	?>
		

	<!-- Styles and links -->
	<?php
		echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
			->prependStylesheet('//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css')
			->prependStylesheet($this->basePath() . '/css/compileLess.php');
	?>
		

	<!-- Head Scripts -->
	<?php
		echo $this->headScript()
			->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
			->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js')
			->appendFile('//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js')
			->appendFile($this->basePath() . '/js/omelettes.js');
	?>
		

</head>