<head>
	<?php
		echo $this->headTitle($this->translate('Tactile CRM'))
			->setSeparator(' - ')
			->setAutoEscape(false);
	?>
		

	<!-- Meta -->
	<?php
		echo $this->headMeta()
			->setCharset('utf-8')
			->appendName('viewport', 'width=device-width, initial-scale=1.0');
	?>
		

	<!-- Styles and links -->
	<link rel="shortcut icon" type="image/vnd.microsoft.icon" sizes="16x16 24x24 32x32 64x64" href="<?php echo $this->basePath() . '/favicon.ico' ?>">
	<?php
		echo $this->headLink()
			->prependStylesheet('//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css')
			->prependStylesheet($this->basePath('/css/tactilecrm.css'));
	?>
		

	<!-- Head Scripts -->
	<?php
		echo $this->headScript()
			->prependFile($this->basePath('/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath('/js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
			->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js')
			->appendFile('//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js')
			->appendFile($this->basePath('/js/omelettes/time.js'))
			->appendFile($this->basePath('/js/omelettes.js'));
	?>

</head>