<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-bottom-collapse">
			<span class="glyphicon glyphicon-info-sign"></span>
		</button>
	</div>
	
	<div class="collapse navbar-collapse navbar-bottom-collapse">
		<ul class="nav navbar-nav">
			<li>
				<a href="<?php #echo $this->url('about'); ?>"><?php echo $this->translate('About'); ?></a>
			</li>
			<li>
				<a href="<?php #echo $this->url('terms'); ?>"><?php echo $this->translate('Privacy & Terms'); ?></a>
			</li>
		</ul>
		<p class="navbar-text">&copy; <a class="navbar-link" href="http://www.omelett.es">omelett.es Ltd</a> <?php echo date('Y'); ?></p>
	</div>
	
</nav>
