<nav class="navbar navbar-fixed-top navbar-inverse navbar-logo" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#tcrm-top-navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $this->url('front'); ?>">
				<div class="brand-logo">
					<img width="40" height="40" class="img-responsive" src="/img/tactilecrm.svg" alt="Tactile CRM logo">
				</div>
				<?php echo $this->translate('Tactile CRM'); ?>
			</a>
		</div>
		<div class="collapse navbar-collapse" id="tcrm-top-navbar">
			<?php echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav')->setPartial('nav/navbar'); ?>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user <?php echo $this->authService()->getIdentity()->isPasswordAuthenticated()? 'text-success' : 'text-warning' ?>"></span> <?php echo $this->escapehtml($this->authService()->getIdentity()->fullName); ?> <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li>
							<a href="<?php echo $this->url('logout'); ?>"><span class="glyphicon glyphicon-log-out"></span> <?php echo $this->translate('Sign out'); ?></a>
						</li>
					</ul>
				</li>
			</ul>
			<form class="navbar-form navbar-right" role="search" action="<?php echo $this->url('search'); ?>">
				<div class="form-group">
					<label for="navbar-search" class="sr-only">Search</label>
					<input id="navbar-search" type="text" class="form-control" placeholder="Search">
				</div>
				<button type="submit" class="btn btn-default">Go</button>
			</form>
		</div>
	</div>
</nav>
